apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: whole-agent-default-deny
  namespace: whole-agent
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector: {}
  egress:
    - to:
      - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-to-database
  namespace: whole-agent
spec:
  podSelector:
    matchLabels:
      app: auth-service
  policyTypes:
    - Egress
  egress:
    - to:
        podSelector:
          matchLabels:
            app: postgres
      ports:
        - protocol: TCP
          port: 5432
